#!/usr/bin/env python3
import sys
from math import sqrt

def open_read_file(file_name):
    """read from file
    add to array
    """
    with open(file_name, "r", encoding="utf-8") as file:
        lines = file.readlines()
    return [int(line) for line in lines]

def find_and_times(n):
    """factor each
    n given
    """
    for i in range(int(sqrt(n)), 0, -1):
        if n % i == 0:
            print("{}={}*{}".format(n, n // i, i))
            break

def fac_list(ls):
    """factor each
    num in ls
    """
    [find_and_times(i) for i in ls]

if len(sys.argv) == 2:
    fac_list(open_read_file(sys.argv[1]))
